### ISSUE TITLE
Cannot send funds from my phone without VPN

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrandroid#127]
When I try to send funds back to the faucet from my phone, I run into problems. The wallet prompts me for the password, and after entering it just hangs on the "Processing..." screen as displayed in the screenshot. After closing and restarting the wallet, the logs don't show any activity of the tx. 

What's even more strange: when I use my phone with VPN, the transaction does _sometimes_ get through (not always). If successful, the tx processing is quick and shows up in the logs.

EDIT: my phone (Moto G5) is running Android 7.0

![image](https://user-images.githubusercontent.com/16287891/45257395-008d3f80-b3a6-11e8-960d-0dc143420c12.png)

**Comment by noahpierau** [comment]
Could it be that some Android settings are disabling outgoing traffic? Maybe the app needs special permissions in order to bypass these standard restrictions?

**Comment by noahpierau** [comment]
It seems that the app simply freezes when I click to confirm the transaction, because even when I enter a wrong password the wallet gets stuck on the "Processing..." screen (as shown above).

**Comment by raedah** [comment]
My guess is it is not related to VPN, but is rather a bug that occurs during sending which only occurs intermittently. After getting back into the app, you can check the wallet log from the settings menu and see if there are any other clues left over from the previous session. Many of the other freezes are caused by db writes and this has a good chance of being the same.

**Comment by noahpierau** [comment]
New release fixed my bug. Indeed it wasn't related to my network. Glad to see it fixed!
