### ISSUE TITLE
Security Password

### ISSUE THREAD

**Issue by denyszayets** [decred/dcrandroid#134]
After Seed confirmation, user will be required to setup a Security PIN. Required to send funds.

OUTDATED
![2 2 1 security password 2x](https://user-images.githubusercontent.com/33739891/45495066-80b5fb00-b740-11e8-9be1-6ce04900ebe5.png)

OUTDATED
![4 5 settings 2x](https://user-images.githubusercontent.com/33739891/45492591-ae984100-b73a-11e8-8ce0-72086d3f3328.png)

**Comment by noahpierau** [comment]
I strongly prefer the word "password" over "private passphrase". I'm not a big fan of required numbers or signs, it's up to the people to come up with strong passwords. We can recommend it, but I don't think it should be a hard requirement. Your money, your responsibility.

**Comment by denyszayets** [comment]
Hi Noah
So initially I had a simple 6 digit pin code, which I thought was a simple idea. So devs brought up the fact that it's easily hackable. Since this device requires initial login I don't think it's a problem to use PIN only.

If we use numeric pin code it makes everything easier. If we're concerned about security, we can always add tentatives limit. Personally, prefer PIN code.

@raedah thoughts?

**Comment by raedah** [comment]
Not clear that the standard 8 chars, 1 uppercase, 1 number, suggestion or requirement is mathematically justifiable. Passwords can be made more difficult simply by making them longer without adding the type requirement. A better solution would be a difficulty meter that indicates how strong the password is. 

For the pin, if a pin is to be used we would need to flush out how its going to work in correlation with the password to unlock the wallet. A possible work flow might be, if the user selects to use a pin, they would still need to type in their password to launch the app. Once launched, they would be running their wallet unlocked (possible security risk) until it is closed. The app would then require the use of the pin in the UI before doing a spend. Because of the potential security risk of running an unlocked wallet and using a pin, we should consider the tradeoff and weigh it against the usability benefits in making a pin available. Being that a pin would not negate the need for a password, it seems that a pin could make a more complicated process that is as well less secure. 

A last possible option would be to use the pin input UI if the user decides to make their wallet password a set of numbers. We would need to prompt the user though that the pin is less secure, and it would be up to their discretion based on the value of their wallet on what level of security they want to use.

**Comment by denyszayets** [comment]
I see your point. How about following:

1. Settings will have an option to choose between PIN or Password to secure their wallet.
2. If user chooses PIN, there will be a message warning them about possible security risk.
3. If they choose password, we will simply display strength of their password without forcing them to utilize specific characters and combinations.

Sounds right?

**Comment by denyszayets** [comment]
**Password Tab selected**
![security password 2x](https://user-images.githubusercontent.com/33739891/46038379-e313e180-c0d8-11e8-9fc2-f2f17199c33d.png)

**Pin Tab selected Create**
![security pin create 2x](https://user-images.githubusercontent.com/33739891/46038399-f626b180-c0d8-11e8-9013-fca84f8b4ac3.png)

**Pin Tab selected Confirm**
![security pin confirmation 2x](https://user-images.githubusercontent.com/33739891/46038413-0179dd00-c0d9-11e8-92bb-9ace32f1324b.png)

**Setting View**
![4 5 settings 2x](https://user-images.githubusercontent.com/33739891/46038479-2f5f2180-c0d9-11e8-997c-2ffd65d18767.png)
