### ISSUE TITLE
Bolt DB memory crash

### ISSUE THREAD

**Issue by C-ollins** [decred/dcrandroid#222]
Bolt db crashes when wallet database size is getting close to 250mb. At that point, it's unable to open wallet because the allocated app memory cannot handle that. The crash usually starts from when the wallet is fetching headers and the wallet db rises to the size which the app's allocated memory cannot handle. Here's the crash log https://bpaste.net/show/61c2f48d8d49

**Comment by raedah** [comment]
noting this via jrick, "i'm skeptical that the issue lies with bolt and not android
this would be better tested by using mmap directly
bolt is not using ram for these allocations. they are memory mapped disk access
the addresses are in the process' virtual address space, and they do not use up any physical memory when you read or write to a memory mapped address, it performs disk i/o"

**Comment by C-ollins** [comment]
Moved to https://github.com/raedahgroup/dcrlibwallet/issues/39
