### ISSUE TITLE
group reused activity code into custom activity class

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrandroid#298]
specifically
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    val decorView = window.decorView
    decorView.systemUiVisibility = WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS or View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR
}
```
in onCreate is reused almost every activity.  moving this to a custom class and extending that class would reduce code and make upkeep easier

**Comment by itswisdomagain** [comment]
Also, when displaying transactions in the history fragment, a call is made to retrieve the best block height every time an item is to be displayed on the list via the `onBindViewHolder` method. See https://github.com/decred/dcrandroid/blob/master/app/src/main/java/com/dcrandroid/adapter/TransactionAdapter.java#L74

There is a class used to track the number of peers, we can also add the best block height to it and update at startup and whenever onBlockAttached is called. Then `TransactionAdapter.onBindViewHolder` can use that value for determining the status of transactions rather than calling `WalletData.getInstance().wallet.getBestBlock()` every time.
